### ISSUE TITLE
Sixel detection

### ISSUE THREAD

**Issue by hackerb9** [uobikiemukot/yaft#43]
Hi! I'm the author of [lsix](https://github.com/hackerb9/lsix/) and I received a [bug report](https://github.com/hackerb9/lsix/issues/25) that my program doesn't work with `yaft` even though it should. It would appear to be a bug in `yaft`'s response to the Send Device Attributes escape sequence. In particular, in response to `ESC` `[` `c`, the response must include a '4' if sixel graphics are supported. 

Here is a patch which fixes that.

    diff --git a/ctrlseq/csi.h b/ctrlseq/csi.h
    index 67fb245..b399516 100644
    --- a/ctrlseq/csi.h
    +++ b/ctrlseq/csi.h
    @@ -398,7 +398,7 @@ void device_attribute(struct terminal_t *term, struct parm_t *parm)
     {
     	/* TODO: refer VT525 DA */
     	(void) parm;
    -	ewrite(term->fd, "\033[?6c", 5); /* "I am a VT102" */
    +	ewrite(term->fd, "\033[?6;4;c", 8); /* "I am a VT102" + SIXEL */
     }
     
     void set_mode(struct terminal_t *term, struct parm_t *parm)
    diff --git a/ctrlseq/esc.h b/ctrlseq/esc.h
    index 324b916..8dbad4d 100644
    --- a/ctrlseq/esc.h
    +++ b/ctrlseq/esc.h
    @@ -75,7 +75,7 @@ void reverse_nl(struct terminal_t *term)
     
     void identify(struct terminal_t *term)
     {
    -	ewrite(term->fd, "\033[?6c", 5); /* "I am a VT102" */
    +	ewrite(term->fd, "\033[?6;4;c", 8); /* "I am a VT102" + SIXEL */
     }
     
     void enter_csi(struct terminal_t *term)

**Comment by uobikiemukot** [comment]
Hi,

yaft uses VT100-style Device Attributes (DA1), because yaft is VT102 capable terminal emulator. (in my thoughts...) If yaft responses "CSI ? 6 ; 4 ; c" as DA1, it means nothing. Just an illegal escape sequence. DA1 with VT-class and some parameters is only available on VT220 and higher.

Please see "Primary DA" in [XTerm Control Sequences](https://invisible-island.net/xterm/ctlseqs/ctlseqs.pdf)

**Comment by hackerb9** [comment]
Oh, right! I knew that but forgot. 

So, if Yaft responds as a VT102, how would a client program go about detecting it has SIXEL capabilities? 

What is the minimum amount needed for Yaft to be able to claim to be VT220 class?

**Comment by uobikiemukot** [comment]
> So, if Yaft responds as a VT102, how would a client program go about detecting it has SIXEL capabilities?

Maybe the only way is to detect `TERM` environment variable.

In my opinion, you don't have to detect SIXEL capability unless your program has a fallback mode (for example, using Select Graphic Rendition (like [ansize](https://github.com/jhchen/ansize)) for non-capable terminal instead of SIXEL). Usually users know whether their terminal has SIXEL capability or not.

> What is the minimum amount needed for Yaft to be able to claim to be VT220 class?

I don't know the difference between VT102 and VT220 exactly. It seems that there is some character set and hardware difference.

- https://www.vt100.net/docs/vt220-rm/appendixa.html
- https://www.vt100.net/docs/vt220-rm/chapter1.html

Roughly VT102 and VT220 support equivalent terminal escape sequences. So, one solution is to append VT220-style Device Attributes functionality to yaft.

**Comment by uobikiemukot** [comment]
@ttdoda told me the detail about VT102/VT220 difference.

- https://vt100.net/emu/fingers/vt102-vt220-finger.html

There are:
- 25 new sequences
- 1 deleted sequence

**Comment by hackerb9** [comment]
Hmm... without hyperlinks from that table, it's hard to tell if 25 new sequences is a lot of work or a little.

Nevermind, though. I've simply put in a check if `TERM == yaft*`, so `lsix` *ought* to work even if yaft remains a VT102 + sixel. (Let me know if it doesn't!)

Why bother checking if a terminal is sixel capable? Because I was getting people telling me `lsix` wasn't working, but it turned out their terminals didn't handle sixel. It seemed friendlier to detect the problem and give them an error message rather than dumping garbage (raw sixel data) on their screen. 

By the way, I'm glad I got notified of this bug because your yaft project looks intriguing. I'm not sure I'm actually going to use it, since it is missing some features I use — for example, I detect the background screen color for `lsix` — but I'm definitely going to watch `yaft` and maybe one day I'll be able to switch.

**Comment by AutumnMeowMeow** [comment]
Would the `CSI ? 4 ; 6 c  ("VT132 with Advanced Video and Graphics")` as noted on https://invisible-island.net/xterm/ctlseqs/ctlseqs.html be an option here?
